1-ridge(L2)---overall data ko normalize krta hai

equation of ridge--> ridge=Loss + alpha||w||**2

loss = acutal value- predicition value


2-lasso(L1)  ---->regression---> predicition

In [1]:
import pandas as pd

In [27]:
df=pd.read_csv('Housing.csv')
df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [5]:
df = df.select_dtypes(include=['int','float'])
df

        price  area  bedrooms  bathrooms  stories  parking
0    13300000  7420         4          2        3        2
1    12250000  8960         4          4        4        3
2    12250000  9960         3          2        2        2
3    12215000  7500         4          2        2        3
4    11410000  7420         4          1        2        2
..        ...   ...       ...        ...      ...      ...
540   1820000  3000         2          1        1        2
541   1767150  2400         3          1        1        0
542   1750000  3620         2          1        1        0
543   1750000  2910         3          1        1        0
544   1750000  3850         3          1        2        0

[545 rows x 6 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   price      545 non-null    int64
 1   area       545 non-null    int64
 2   bedrooms   545 non-null    int64
 3   bathrooms  545 non-null    int64
 4   stories    545 non-null    int64
 5   parking    545 non-null    int64
dtypes: int64(6)
memory usage: 25.7 KB

In [7]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [8]:
x=df[['area','bedrooms','bathrooms','parking']]
y=df[['price']]

In [16]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.linear_model import *
from sklearn.metrics import r2_score

In [20]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=1)
y_test

       price
62   7070000
247  4550000
142  5600000
107  6125000
483  2940000
..       ...
256  4480000
401  3500000
105  6160000
536  1960000
341  3850000

[273 rows x 1 columns]

In [21]:
lr=LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [29]:
x_test_predict=lr.predict(x_test)
x_test_predict

array([[ 6424491.27533942],
       [ 6618857.18313301],
       [ 7887215.69465224],
       [ 4560082.56621231],
       [ 4627038.26146254],
       [ 3258261.50042792],
       [ 3483110.3476271 ],
       [ 5667265.9078883 ],
       [ 2949235.2146576 ],
       [ 4072507.7597747 ],
       [ 3614065.15288175],
       [ 4328789.89203619],
       [ 4003835.25182574],
       [ 3959675.16181054],
       [ 6940721.24117006],
       [ 7178118.43374559],
       [ 4188666.750469  ],
       [ 4082331.59581542],
       [ 6199642.42814024],
       [ 3275086.26487541],
       [ 3544915.60478116],
       [ 5836864.2922242 ],
       [ 6090532.88246392],
       [ 3447587.93743917],
       [ 4850936.76300502],
       [ 5936859.11792162],
       [ 3400703.33808835],
       [ 6997429.67656161],
       [ 5922704.9271604 ],
       [ 3092207.70880331],
       [ 5783696.71489741],
       [ 6188810.89546262],
       [ 4269467.91462287],
       [ 4712825.28006509],
       [ 5927244.96680877],
       [ 3007606.84641422],
       [ 5646828.73915112],
       [ 3292200.775529  ],
       [ 4141180.26772366],
       [ 4874549.03628488],
       [ 4392311.96188898],
       [ 3899056.06086992],
       [ 3457888.81363152],
       [ 4388878.33649153],
       [ 5719831.60182058],
       [ 3515783.40523651],
       [ 4727745.93786833],
       [ 3884844.51912851],
       [ 2880562.70670864],
       [ 3677640.83906819],
       [ 5388722.56152359],
       [ 3789866.77323108],
       [ 3223925.24645344],
       [ 3845888.48354314],
       [ 5278789.19782506],
       [ 4075941.38517215],
       [ 3052243.97658104],
       [ 4393498.11810243],
       [ 4343656.93350578],
       [ 4029346.53202741],
       [ 5660086.20058929],
       [ 5456151.56227891],
       [ 3271996.00201771],
       [ 4453532.94622411],
       [ 3784083.22638907],
       [ 3021341.34800401],
       [ 4451392.70970742],
       [ 3719321.38398918],
       [ 4890401.06409334],
       [ 3675446.98621784],
       [ 4347144.17523688],
       [ 4621887.82336637],
       [ 5753271.12647201],
       [ 3258261.50042792],
       [ 4764329.6610268 ],
       [ 2769313.24383133],
       [ 3749162.69959566],
       [ 5933902.5326758 ],
       [ 5463018.81307381],
       [ 3217057.99565854],
       [ 4402135.7979297 ],
       [ 3560897.57555496],
       [ 6152757.82878941],
       [ 5814599.34347445],
       [ 4821515.13656997],
       [ 5145042.3909721 ],
       [ 3385782.68028511],
       [ 3114049.2337351 ],
       [ 5009780.26061068],
       [ 4261249.92396703],
       [ 3757800.37942294],
       [ 5044116.51458516],
       [ 3317110.17233615],
       [ 6521818.94268141],
       [ 3725234.55448083],
       [ 4151958.18406762],
       [ 8116264.6342909 ],
       [ 4723126.15625743],
       [ 5975922.3861743 ],
       [ 6175499.81769079],
       [ 3344102.13536411],
       [ 7215411.2729659 ],
       [ 3426986.18505449],
       [ 3725711.59463246],
       [ 3761764.66130566],
       [ 5248051.15289554],
       [ 6903001.24348525],
       [ 5038542.65267102],
       [ 4450206.55349397],
       [ 4451816.13352539],
       [ 4604719.69637913],
       [ 4097020.17770846],
       [ 3856189.35973548],
       [ 3447587.93743917],
       [ 4894330.3859782 ],
       [ 3560897.57555496],
       [ 3605534.70572178],
       [ 6170402.99592828],
       [ 6233814.09846721],
       [ 6548101.78964755],
       [ 6432651.91501507],
       [ 3205517.34691909],
       [ 3677640.83906819],
       [ 3900826.4899023 ],
       [ 3299465.00519729],
       [ 4186294.4380421 ],
       [ 6235107.48734797],
       [ 5836864.2922242 ],
       [ 3718844.34383756],
       [ 3888755.18467758],
       [ 4374559.56208281],
       [ 4592648.39115441],
       [ 3564331.2009524 ],
       [ 3092207.70880331],
       [ 5318806.54638099],
       [ 3620455.36352502],
       [ 4983474.70334651],
       [ 3369644.64091711],
       [ 5885354.7369599 ],
       [ 5714916.97428115],
       [ 8820634.88091935],
       [ 7934759.52837778],
       [ 4587921.3768762 ],
       [ 4391304.26525208],
       [ 6918933.33257193],
       [ 3190066.03263058],
       [ 4681502.96231663],
       [ 4903922.14610872],
       [ 5151852.2907868 ],
       [ 4592648.39115441],
       [ 2922243.25162964],
       [ 3065978.47817083],
       [ 3756270.86066974],
       [ 4876666.56250355],
       [ 5876297.3679612 ],
       [ 3154012.96595738],
       [ 4838549.58594533],
       [ 4475008.39831813],
       [ 3092207.70880331],
       [ 3540295.82317027],
       [ 3265128.75122281],
       [ 3395606.51632583],
       [ 4764329.6610268 ],
       [ 6008545.5620966 ],
       [ 6175499.81769079],
       [ 3237659.74804323],
       [ 7117499.33280498],
       [ 3426986.18505449],
       [ 5321820.48260701],
       [ 3047570.57863649],
       [ 3757800.37942294],
       [ 5799514.1020237 ],
       [ 3312646.45931947],
       [ 3576504.95843769],
       [ 5107749.55175179],
       [ 4436472.05190418],
       [ 5493501.75247941],
       [ 5236399.53684224],
       [ 5804775.50743372],
       [ 5188436.01394528],
       [ 3715410.71844011],
       [ 5596930.20357428],
       [ 5927851.63061003],
       [ 3268562.37662026],
       [ 4422737.55031439],
       [ 5704616.0980888 ],
       [ 6429298.35089585],
       [ 3567287.78619823],
       [ 5514103.5048641 ],
       [ 6252332.9653154 ],
       [ 5832137.277946  ],
       [ 5419675.07178774],
       [ 4940875.67675152],
       [ 4811423.9453055 ],
       [ 6342084.26580067],
       [ 3409341.01791562],
       [ 4973361.1210997 ],
       [ 4091339.08312701],
       [ 4893036.99709745],
       [ 5866103.72443616],
       [ 3326934.00837687],
       [ 3715410.71844011],
       [ 4038171.50580022],
       [ 4232594.764574  ],
       [ 3252767.699792  ],
       [ 3136844.83897014],
       [ 3395606.51632583],
       [ 5831767.47046169],
       [ 7553676.99094817],
       [10543787.90859948],
       [ 3500278.47461434],
       [ 5751496.96279309],
       [ 9154173.58462342],
       [ 2873218.41576212],
       [ 5532565.02073209],
       [ 4909785.43491326],
       [ 3958721.08150729],
       [ 3641587.77239498],
       [ 6230144.34319733],
       [ 4450206.55349397],
       [ 8781621.49435378],
       [ 4041128.09104605],
       [ 5036772.22363864],
       [ 5112789.02253412],
       [ 4182383.77249303],
       [ 5306899.82480377],
       [ 3409341.01791562],
       [ 8409069.40408414],
       [ 3083146.60515807],
       [ 3051766.93642942],
       [ 3893482.19895578],
       [ 3993534.3756334 ],
       [ 4125144.68061621],
       [ 6008545.5620966 ],
       [ 5298204.79399631],
       [ 6530933.66266031],
       [ 4187480.59425555],
       [ 3420118.93425959],
       [ 3412774.64331307],
       [ 3608968.33111923],
       [ 3677640.83906819],
       [ 3944986.5799175 ],
       [ 5249161.30179299],
       [ 5482014.72007362],
       [ 3052243.97658104],
       [ 5648545.55184984],
       [ 5939922.93583476],
       [ 3052243.97658104],
       [ 4366029.11492284],
       [ 3591800.20413199],
       [ 4077604.58153722],
       [ 3223925.24645344],
       [ 6278138.77212992],
       [ 4175516.52169814],
       [ 3684031.04971146],
       [ 3385782.68028511],
       [ 3550596.69936261],
       [ 3375481.80409277],
       [ 4690350.64638746],
       [ 4008932.07358826],
       [ 3409341.01791562],
       [ 6029674.23632002],
       [ 6446863.45675649],
       [ 4072507.7597747 ],
       [ 4875922.48644386],
       [ 3344579.17551574],
       [ 6076985.99413536],
       [ 3437287.06124683],
       [ 4426063.94304453],
       [ 6663017.27314821],
       [ 3900826.4899023 ],
       [ 4197072.35438607],
       [ 5055183.85781952]])

In [30]:
r2_score(y_test,x_test_predict)

0.5065866558524543

In [32]:
x_test_predict_ridge=lr.predict(x_test)
r2_score(y_test,x_test_predict_ridge)

0.5065866558524543

In [33]:
lasso_regression=Lasso(alpha=0.1)
lasso_regression.fit(x_train,y_train)

Lasso(alpha=0.1)

In [34]:
x_test_predict_lasso=lasso_regression.predict(x_test)
r2_score(y_test,x_test_predict_lasso)

0.5065866404289534

In [35]:
# x=df[['area','bedrooms','bathrooms','parking']]
# y=df[['price']]
pred=lr.predict([[5000,3,2,1]])
pred

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[5665183.02235181]])